"""Liquid — Zapier for AI agents. Connect to any API on the fly."""

from importlib.metadata import version as _pkg_version

__version__ = _pkg_version("liquid-api")

from liquid.adapters import BundledAdapterRegistry, list_bundled_adapters, load_bundled_adapter
from liquid.agent_tools import (
    aggregate,
    check_quota,
    check_rate_limit,
    fetch_changes_since,
    fetch_until,
    get_adapter_info,
    health_check,
    list_adapters,
    search_nl,
    text_search,
    to_tools,
)
from liquid.agent_tools import estimate_fetch as estimate_fetch_tool
from liquid.auth.schemes import (
    ApiKeyAuth,
    AuthScheme,
    AwsSigV4Auth,
    BasicAuth,
    BearerAuth,
    HMACAuth,
    OAuth2Auth,
)
from liquid.cache import InMemoryCache
from liquid.catalog import HttpCatalogRegistry
from liquid.client import Liquid
from liquid.connectors import HomeAssistantConnector, SmartcarConnector, TelegramConnector
from liquid.diff_sync import FetchChangesResult
from liquid.estimate import FetchEstimate, estimate_fetch
from liquid.evolution import EvolutionKind, EvolutionSignal, extract_signals
from liquid.exceptions import (
    ActionNotVerifiedError,
    AuthError,
    AuthSetupError,
    DiscoveryError,
    EndpointGoneError,
    FieldNotFoundError,
    LiquidError,
    MappingError,
    RateLimitError,
    Recovery,
    ServiceDownError,
    SyncRuntimeError,
    ToolCall,
    VaultError,
)
from liquid.intent import CANONICAL_INTENTS, Intent, IntentConfig, get_intent
from liquid.intent import list_intents as list_canonical_intents
from liquid.llm import (
    AnthropicBackend,
    CallableBackend,
    GeminiBackend,
    LiteLLMBackend,
    OpenAICompatibleBackend,
    llm_from_env,
)
from liquid.models import (
    ActionConfig,
    ActionError,
    ActionErrorType,
    ActionMapping,
    ActionResult,
    AdapterConfig,
    APISchema,
    AuthRequirement,
    BatchErrorPolicy,
    BatchResult,
    DeliveryResult,
    Endpoint,
    EndpointKind,
    FieldMapping,
    MappedRecord,
    SyncConfig,
    SyncResult,
)
from liquid.models.response import FetchMeta, FetchResponse, FetchUntilResult, SearchNLResult
from liquid.normalize import (
    Email,
    FileAttachment,
    GeoPoint,
    Money,
    PaginationEnvelope,
    PersonName,
    Phone,
    PostalAddress,
    Tag,
    UserRef,
    normalize_datetime,
    normalize_email,
    normalize_file_attachment,
    normalize_geo_point,
    normalize_id,
    normalize_money,
    normalize_pagination,
    normalize_person_name,
    normalize_phone,
    normalize_postal_address,
    normalize_response,
    normalize_tags,
    normalize_user_ref,
)
from liquid.observability import EventKind, EventStore, FetchEvent, InMemoryEventStore
from liquid.persistence import FileAdapterRegistry, FileVault
from liquid.protocols import AdapterRegistry, CacheStore, DataSink, KnowledgeStore, LLMBackend, Vault
from liquid.query import (
    AggregateError,
    QueryError,
    aggregate_async,
    aggregate_records,
    apply_query,
    search_async,
    search_records,
    validate_query,
)
from liquid.query.nl import NLCompilationCache, NLCompileError
from liquid.sense_loop import merge_senses, react
from liquid.streaming import SSEEvent, parse_ndjson, parse_sse
from liquid.sync.known_limits import infer_limits, lookup_known_limits
from liquid.sync.quota import QuotaInfo
from liquid.sync.rate_limiter import RateLimiter
from liquid.tools import adapter_to_tools
from liquid.transport.manifest import DialectManifest, register_sql_manifest
from liquid.validation import MismatchKind, ResponseValidator, SchemaMismatchSignal
from liquid.verbosity import VerbosityLevel, apply_verbosity
from liquid.webhooks import (
    DuplicateEventError,
    GenericHMACWebhookVerifier,
    GitHubWebhookVerifier,
    IdempotencyStore,
    InMemoryIdempotencyStore,
    InvalidSignatureError,
    ShopifyWebhookVerifier,
    SlackWebhookVerifier,
    StripeWebhookVerifier,
    WebhookEvent,
    WebhookVerificationError,
    WebhookVerifier,
    verify_webhook,
)

__all__ = [
    "CANONICAL_INTENTS",
    "APISchema",
    "ActionConfig",
    "ActionError",
    "ActionErrorType",
    "ActionMapping",
    "ActionNotVerifiedError",
    "ActionResult",
    "AdapterConfig",
    "AdapterRegistry",
    "AggregateError",
    "AnthropicBackend",
    "ApiKeyAuth",
    "AuthError",
    "AuthRequirement",
    "AuthScheme",
    "AuthSetupError",
    "AwsSigV4Auth",
    "BasicAuth",
    "BatchErrorPolicy",
    "BatchResult",
    "BearerAuth",
    "BundledAdapterRegistry",
    "CacheStore",
    "CallableBackend",
    "DataSink",
    "DeliveryResult",
    "DialectManifest",
    "DiscoveryError",
    "DuplicateEventError",
    "Email",
    "Endpoint",
    "EndpointGoneError",
    "EndpointKind",
    "EventKind",
    "EventStore",
    "EvolutionKind",
    "EvolutionSignal",
    "FetchChangesResult",
    "FetchEstimate",
    "FetchEvent",
    "FetchMeta",
    "FetchResponse",
    "FetchUntilResult",
    "FieldMapping",
    "FieldNotFoundError",
    "FileAdapterRegistry",
    "FileAttachment",
    "FileVault",
    "GeminiBackend",
    "GenericHMACWebhookVerifier",
    "GeoPoint",
    "GitHubWebhookVerifier",
    "HMACAuth",
    "HomeAssistantConnector",
    "HttpCatalogRegistry",
    "IdempotencyStore",
    "InMemoryCache",
    "InMemoryEventStore",
    "InMemoryIdempotencyStore",
    "Intent",
    "IntentConfig",
    "InvalidSignatureError",
    "KnowledgeStore",
    "LLMBackend",
    "Liquid",
    "LiquidError",
    "LiteLLMBackend",
    "MappedRecord",
    "MappingError",
    "MismatchKind",
    "Money",
    "NLCompilationCache",
    "NLCompileError",
    "OAuth2Auth",
    "OpenAICompatibleBackend",
    "PaginationEnvelope",
    "PersonName",
    "Phone",
    "PostalAddress",
    "QueryError",
    "QuotaInfo",
    "RateLimitError",
    "RateLimiter",
    "Recovery",
    "ResponseValidator",
    "SSEEvent",
    "SchemaMismatchSignal",
    "SearchNLResult",
    "ServiceDownError",
    "ShopifyWebhookVerifier",
    "SlackWebhookVerifier",
    "SmartcarConnector",
    "StripeWebhookVerifier",
    "SyncConfig",
    "SyncResult",
    "SyncRuntimeError",
    "Tag",
    "TelegramConnector",
    "ToolCall",
    "UserRef",
    "Vault",
    "VaultError",
    "VerbosityLevel",
    "WebhookEvent",
    "WebhookVerificationError",
    "WebhookVerifier",
    "adapter_to_tools",
    "aggregate",
    "aggregate_async",
    "aggregate_records",
    "apply_query",
    "apply_verbosity",
    "check_quota",
    "check_rate_limit",
    "estimate_fetch",
    "estimate_fetch_tool",
    "extract_signals",
    "fetch_changes_since",
    "fetch_until",
    "get_adapter_info",
    "get_intent",
    "health_check",
    "infer_limits",
    "list_adapters",
    "list_bundled_adapters",
    "list_canonical_intents",
    "llm_from_env",
    "load_bundled_adapter",
    "lookup_known_limits",
    "merge_senses",
    "normalize_datetime",
    "normalize_email",
    "normalize_file_attachment",
    "normalize_geo_point",
    "normalize_id",
    "normalize_money",
    "normalize_pagination",
    "normalize_person_name",
    "normalize_phone",
    "normalize_postal_address",
    "normalize_response",
    "normalize_tags",
    "normalize_user_ref",
    "parse_ndjson",
    "parse_sse",
    "react",
    "register_sql_manifest",
    "search_async",
    "search_nl",
    "search_records",
    "text_search",
    "to_tools",
    "validate_query",
    "verify_webhook",
]
