import type {
  EntityId,
  ProfileBinding,
  TenantId,
  Timestamp,
} from "./common.js";

/**
 * The base shape of every node in the entity graph.
 *
 * Architecture rule (architecture.md, Layer 1):
 *   Nodes hold identity + stable attributes only.
 *   Everything contextual rides on typed edges.
 *
 * If you find yourself wanting to add a field here that varies by tool,
 * by relationship, or by lifecycle — it's an edge, not a node attribute.
 */
export interface NodeBase {
  /** Globally unique, never reused. Generated by the substrate at write-time. */
  readonly id: EntityId;

  /** Tenant ownership. Partition key at every layer. */
  readonly tenantId: TenantId;

  /** Tier-1 type + profile binding. Resolves "what kind of thing is this". */
  readonly profile: ProfileBinding;

  /** When the node was first created. Never mutated. */
  readonly createdAt: Timestamp;

  /** When any field on the node was last changed. */
  readonly updatedAt: Timestamp;

  /**
   * Schema version of the profile this node was written under.
   * Profiles migrate; tools branch on this when reading old data.
   */
  readonly schemaVersion: number;

  /**
   * Monotonic row revision for optimistic concurrency.
   *
   * This is intentionally separate from schemaVersion: schemaVersion tracks the
   * profile contract, while revision changes whenever the stored identity bag
   * changes.
   */
  readonly revision: number;

  /**
   * Stable identity attributes only. Profile-specific concrete shape
   * lives in the profile's specialized type, which extends NodeBase.
   *
   * Day-1 baseline: a small key-value bag of declared fields.
   * Profile types tighten this with concrete required fields.
   */
  readonly identity: Readonly<Record<string, unknown>>;
}
